export const participantes = [
  {
    id: 1,
    nome: "João Silva",
    email: "joao.silva@email.com",
    status: "Confirmada",
    funcao: "Participante",
    eventosInscritosIds: [1, 3], 
  },
  {
    id: 2,
    nome: "Maria Souza",
    email: "maria.souza@email.com",
    status: "Confirmada",
    funcao: "Participante",
    eventosInscritosIds: [1, 2], 
  },
  {
    id: 3,
    nome: "Pedro Alves",
    email: "pedro.alves@email.com",
    status: "Pendente",
    funcao: "Participante",
    eventosInscritosIds: [3], 
  },
  {
    id: 4,
    nome: "Ana Costa",
    email: "ana.costa@empresa.com",
    status: "Confirmada",
    funcao: "Professor",
    eventosInscritosIds: [1], 
  },
  {
    id: 5,
    nome: "Dr. Rafael Mendes",
    email: "rafael.mendes@uni.edu",
    status: "Confirmada",
    funcao: "Palestrante",
    eventosInscritosIds: [3], 
  },
  {
    id: 6,
    nome: "Júlia Ferreira",
    email: "julia.ferreira@email.com",
    status: "Pendente",
    funcao: "Participante",
    eventosInscritosIds: [2, 4], 
  },
  {
    id: 7,
    nome: "Lucas Fernandes",
    email: "lucas.fernandes@tech.com",
    status: "Confirmada",
    funcao: "Professor",
    eventosInscritosIds: [4], 
  },
];